export default {
    "BAD_FORECAST_OFFICE": "電文の形式が不正です(発信官署)",
    "BAD_DRILL_TYPE": "電文の形式が不正です(識別符)",
    "BAD_CONTINUE_FLAG": "電文の形式が不正です",
    "BAD_EARTHQUAKE_ID": "電文の形式が不正です(地震識別番号)",
    "BAD_STATUS": "電文の形式が不正です",
    "BAD_FINAL_FALG": "電文の形式が不正です",
    "BAD_EEW_ID": "電文の形式が不正です(高度利用者向け緊急地震速報の番号)",
    "BAD_EPICENTER_NAME": "電文の形式が不正です(震央の名称)",
    "BAD_EPICENTER_COORDINATE": "電文の形式が不正です(震央の位置)",
    "BAD_DEPTH": "電文の形式が不正です(震源の深さ)",
    "BAD_MAGNITUDE": "電文の形式が不正です(マグニチュード)",
    "BAD_INTENSITY": "電文の形式が不正です(最大予測震度)",
    "BAD_POSITION_PROBABILITY": "電文の形式が不正です(震央の確からしさ)",
    "BAD_DEPTH_PROBABILITY": "電文の形式が不正です(震源の深さの確からしさ)",
    "BAD_MAGNITUDE_PROBABILITY": "電文の形式が不正です(マグニチュードの確からしさ)",
    "BAD_HYPOCENTER_POSITION_PROBABILITY": "電文の形式が不正です(震央の確からしさ[気象庁の部内システムでの利用])",
    "BAD_MAGNITUDE_OBSERVE_POINTS": "電文の形式が不正です(マグニチュード使用観測点)",
    "BAD_LAND_OR_SEA_FLAG": "電文の形式が不正です(震央位置の海陸判定)",
    "BAD_SEISMIC_INTENSITY_CHANGE_FLAG": "電文の形式が不正です(最大予測震度の変化)",
    "BAD_FORECAST_METHOD": "電文の形式が不正です(予測手法)",
    "BAD_SEISMIC_INTENSITY_CHANGE_REASON": "電文の形式が不正です(最大予測震度の変化の理由)",
    "UNKNOWN_ERROR": ""
}